AWSTemplateFormatVersion: 2010-09-09
Description: Setup 
Resources:
  Jenkins:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-1a7f6d7e
      InstanceType: t2.nano
      KeyName: ec2-test
      SecurityGroups:
        - !Ref JenkinsSecurityGroup
      UserData: !Base64 |
        #!/bin/bash -x
        yum update –y
        yum -y install git
        su - ec2-user <<EOF
        sudo yum install java-1.8.0 -y
        sudo yum remove java-1.7.0-openjdk -y
        sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
        sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
        sudo yum install jenkins -y
        sudo service jenkins start
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Jenkins Ingress
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
Outputs:
  HostName:
    Description: Host Name of instance where service is running
    Value: !GetAtt Jenkins.PublicDnsName